# fly.toml app configuration file generated for backend-sparkling-shape-3180 on 2025-10-17T19:16:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-sparkling-shape-3180'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
